--
-- PostgreSQL database dump
--

-- Dumped from database version 16.9
-- Dumped by pg_dump version 16.9

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: sexe_type; Type: TYPE; Schema: public; Owner: postgres
--

CREATE TYPE public.sexe_type AS ENUM (
    'F',
    'M'
);


ALTER TYPE public.sexe_type OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO postgres;

--
-- Name: administration; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.administration (
    id_admin integer NOT NULL,
    username text NOT NULL,
    password text NOT NULL,
    description text
);


ALTER TABLE public.administration OWNER TO postgres;

--
-- Name: administration_id_admin_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.administration ALTER COLUMN id_admin ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.administration_id_admin_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: administration_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.administration_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.administration_id_seq OWNER TO postgres;

--
-- Name: bacheliers_id_bachelier_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.bacheliers_id_bachelier_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.bacheliers_id_bachelier_seq OWNER TO postgres;

--
-- Name: bacheliers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.bacheliers (
    id_bachelier integer DEFAULT nextval('public.bacheliers_id_bachelier_seq'::regclass) NOT NULL,
    annee date NOT NULL,
    numero_candidat text NOT NULL,
    moyenne double precision NOT NULL,
    id_personne integer,
    id_option integer,
    id_centre integer,
    id_etablissement integer,
    id_mention integer
);


ALTER TABLE public.bacheliers OWNER TO postgres;

--
-- Name: centres_id_centre_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.centres_id_centre_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.centres_id_centre_seq OWNER TO postgres;

--
-- Name: centres; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.centres (
    id_centre integer DEFAULT nextval('public.centres_id_centre_seq'::regclass) NOT NULL,
    nom_centre text NOT NULL,
    id_province integer
);


ALTER TABLE public.centres OWNER TO postgres;

--
-- Name: etablissements_id_etablissement_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.etablissements_id_etablissement_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.etablissements_id_etablissement_seq OWNER TO postgres;

--
-- Name: etablissements; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.etablissements (
    id_etablissement integer DEFAULT nextval('public.etablissements_id_etablissement_seq'::regclass) NOT NULL,
    nom_etablissement text NOT NULL
);


ALTER TABLE public.etablissements OWNER TO postgres;

--
-- Name: historique; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.historique (
    id_historique integer NOT NULL,
    admin_id integer,
    date_evenement timestamp without time zone DEFAULT now(),
    description text,
    id_province integer NOT NULL
);


ALTER TABLE public.historique OWNER TO postgres;

--
-- Name: historique_id_historique_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.historique ALTER COLUMN id_historique ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.historique_id_historique_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: historique_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.historique_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.historique_id_seq OWNER TO postgres;

--
-- Name: matieres_id_matiere_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.matieres_id_matiere_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.matieres_id_matiere_seq OWNER TO postgres;

--
-- Name: matieres; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.matieres (
    id_matiere integer DEFAULT nextval('public.matieres_id_matiere_seq'::regclass) NOT NULL,
    nom_matiere text NOT NULL
);


ALTER TABLE public.matieres OWNER TO postgres;

--
-- Name: mentions_id_mention_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.mentions_id_mention_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.mentions_id_mention_seq OWNER TO postgres;

--
-- Name: mentions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.mentions (
    id_mention integer DEFAULT nextval('public.mentions_id_mention_seq'::regclass) NOT NULL,
    nom_mention text NOT NULL,
    min integer DEFAULT 0,
    max integer DEFAULT 20
);


ALTER TABLE public.mentions OWNER TO postgres;

--
-- Name: notes_id_note_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.notes_id_note_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.notes_id_note_seq OWNER TO postgres;

--
-- Name: notes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.notes (
    id_note integer DEFAULT nextval('public.notes_id_note_seq'::regclass) NOT NULL,
    valeur_note double precision NOT NULL,
    est_optionnel boolean DEFAULT false,
    id_matiere integer,
    id_bachelier integer
);


ALTER TABLE public.notes OWNER TO postgres;

--
-- Name: options_id_optioin_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.options_id_optioin_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.options_id_optioin_seq OWNER TO postgres;

--
-- Name: options; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.options (
    id_option integer DEFAULT nextval('public.options_id_optioin_seq'::regclass) NOT NULL,
    serie text
);


ALTER TABLE public.options OWNER TO postgres;

--
-- Name: personnes_id_personne_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.personnes_id_personne_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.personnes_id_personne_seq OWNER TO postgres;

--
-- Name: personnes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.personnes (
    id_personne integer DEFAULT nextval('public.personnes_id_personne_seq'::regclass) NOT NULL,
    nom_prenom text NOT NULL,
    date_naissance date NOT NULL,
    lieu_naissance text NOT NULL
);


ALTER TABLE public.personnes OWNER TO postgres;

--
-- Name: provinces_id_province_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.provinces_id_province_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.provinces_id_province_seq OWNER TO postgres;

--
-- Name: provinces; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.provinces (
    id_province integer DEFAULT nextval('public.provinces_id_province_seq'::regclass) NOT NULL,
    nom_province text NOT NULL
);


ALTER TABLE public.provinces OWNER TO postgres;

--
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
20251008081231_first migrations	9.0.7
\.


--
-- Data for Name: administration; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.administration (id_admin, username, password, description) FROM stdin;
\.


--
-- Data for Name: bacheliers; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.bacheliers (id_bachelier, annee, numero_candidat, moyenne, id_personne, id_option, id_centre, id_etablissement, id_mention) FROM stdin;
\.


--
-- Data for Name: centres; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.centres (id_centre, nom_centre, id_province) FROM stdin;
\.


--
-- Data for Name: etablissements; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.etablissements (id_etablissement, nom_etablissement) FROM stdin;
\.


--
-- Data for Name: historique; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.historique (id_historique, admin_id, date_evenement, description, id_province) FROM stdin;
\.


--
-- Data for Name: matieres; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.matieres (id_matiere, nom_matiere) FROM stdin;
\.


--
-- Data for Name: mentions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.mentions (id_mention, nom_mention, min, max) FROM stdin;
\.


--
-- Data for Name: notes; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.notes (id_note, valeur_note, est_optionnel, id_matiere, id_bachelier) FROM stdin;
\.


--
-- Data for Name: options; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.options (id_option, serie) FROM stdin;
\.


--
-- Data for Name: personnes; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.personnes (id_personne, nom_prenom, date_naissance, lieu_naissance) FROM stdin;
\.


--
-- Data for Name: provinces; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.provinces (id_province, nom_province) FROM stdin;
\.


--
-- Name: administration_id_admin_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.administration_id_admin_seq', 1, false);


--
-- Name: administration_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.administration_id_seq', 1, false);


--
-- Name: bacheliers_id_bachelier_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.bacheliers_id_bachelier_seq', 1, false);


--
-- Name: centres_id_centre_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.centres_id_centre_seq', 1, false);


--
-- Name: etablissements_id_etablissement_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.etablissements_id_etablissement_seq', 1, false);


--
-- Name: historique_id_historique_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.historique_id_historique_seq', 1, false);


--
-- Name: historique_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.historique_id_seq', 1, false);


--
-- Name: matieres_id_matiere_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.matieres_id_matiere_seq', 1, false);


--
-- Name: mentions_id_mention_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.mentions_id_mention_seq', 1, false);


--
-- Name: notes_id_note_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.notes_id_note_seq', 1, false);


--
-- Name: options_id_optioin_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.options_id_optioin_seq', 1, false);


--
-- Name: personnes_id_personne_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.personnes_id_personne_seq', 1, false);


--
-- Name: provinces_id_province_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.provinces_id_province_seq', 1, false);


--
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- Name: administration administration_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.administration
    ADD CONSTRAINT administration_pkey PRIMARY KEY (id_admin);


--
-- Name: centres centres_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.centres
    ADD CONSTRAINT centres_pkey PRIMARY KEY (id_centre);


--
-- Name: etablissements etablissements_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.etablissements
    ADD CONSTRAINT etablissements_pkey PRIMARY KEY (id_etablissement);


--
-- Name: historique historique_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.historique
    ADD CONSTRAINT historique_pkey PRIMARY KEY (id_historique);


--
-- Name: matieres matieres_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.matieres
    ADD CONSTRAINT matieres_pkey PRIMARY KEY (id_matiere);


--
-- Name: mentions mentions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mentions
    ADD CONSTRAINT mentions_pkey PRIMARY KEY (id_mention);


--
-- Name: notes notes_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notes
    ADD CONSTRAINT notes_pkey PRIMARY KEY (id_note);


--
-- Name: options options_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.options
    ADD CONSTRAINT options_pkey PRIMARY KEY (id_option);


--
-- Name: personnes personnes_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.personnes
    ADD CONSTRAINT personnes_pkey PRIMARY KEY (id_personne);


--
-- Name: bacheliers pk_bacheliers; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.bacheliers
    ADD CONSTRAINT pk_bacheliers PRIMARY KEY (id_bachelier);


--
-- Name: provinces provinces_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.provinces
    ADD CONSTRAINT provinces_pkey PRIMARY KEY (id_province);


--
-- Name: IX_bacheliers_id_centre; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_bacheliers_id_centre" ON public.bacheliers USING btree (id_centre);


--
-- Name: IX_bacheliers_id_etablissement; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_bacheliers_id_etablissement" ON public.bacheliers USING btree (id_etablissement);


--
-- Name: IX_bacheliers_id_mention; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_bacheliers_id_mention" ON public.bacheliers USING btree (id_mention);


--
-- Name: IX_bacheliers_id_option; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_bacheliers_id_option" ON public.bacheliers USING btree (id_option);


--
-- Name: IX_bacheliers_id_personne; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_bacheliers_id_personne" ON public.bacheliers USING btree (id_personne);


--
-- Name: IX_centres_id_province; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_centres_id_province" ON public.centres USING btree (id_province);


--
-- Name: IX_historique_admin_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_historique_admin_id" ON public.historique USING btree (admin_id);


--
-- Name: IX_historique_id_province; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_historique_id_province" ON public.historique USING btree (id_province);


--
-- Name: IX_notes_id_bachelier; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_notes_id_bachelier" ON public.notes USING btree (id_bachelier);


--
-- Name: IX_notes_id_matiere; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_notes_id_matiere" ON public.notes USING btree (id_matiere);


--
-- Name: administration_username_key; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX administration_username_key ON public.administration USING btree (username);


--
-- Name: bacheliers bacheliers_centre_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.bacheliers
    ADD CONSTRAINT bacheliers_centre_fkey FOREIGN KEY (id_centre) REFERENCES public.centres(id_centre);


--
-- Name: bacheliers bacheliers_etablissement_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.bacheliers
    ADD CONSTRAINT bacheliers_etablissement_fkey FOREIGN KEY (id_etablissement) REFERENCES public.etablissements(id_etablissement);


--
-- Name: bacheliers bacheliers_id_personne_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.bacheliers
    ADD CONSTRAINT bacheliers_id_personne_fkey FOREIGN KEY (id_personne) REFERENCES public.personnes(id_personne);


--
-- Name: bacheliers bacheliers_mention_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.bacheliers
    ADD CONSTRAINT bacheliers_mention_fkey FOREIGN KEY (id_mention) REFERENCES public.mentions(id_mention);


--
-- Name: bacheliers bacheliers_serie_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.bacheliers
    ADD CONSTRAINT bacheliers_serie_fkey FOREIGN KEY (id_option) REFERENCES public.options(id_option);


--
-- Name: centres fk_centres_provinces; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.centres
    ADD CONSTRAINT fk_centres_provinces FOREIGN KEY (id_province) REFERENCES public.provinces(id_province);


--
-- Name: historique fk_historique_provinces; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.historique
    ADD CONSTRAINT fk_historique_provinces FOREIGN KEY (id_province) REFERENCES public.provinces(id_province);


--
-- Name: historique historique_admin_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.historique
    ADD CONSTRAINT historique_admin_id_fkey FOREIGN KEY (admin_id) REFERENCES public.administration(id_admin);


--
-- Name: notes notes_id_bachelier_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notes
    ADD CONSTRAINT notes_id_bachelier_fkey FOREIGN KEY (id_bachelier) REFERENCES public.bacheliers(id_bachelier);


--
-- Name: notes notes_id_matiere_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notes
    ADD CONSTRAINT notes_id_matiere_fkey FOREIGN KEY (id_matiere) REFERENCES public.matieres(id_matiere);


--
-- PostgreSQL database dump complete
--

